// 자동 생성 파일. tools/update_data.py 가 매번 덮어씁니다.
// 마지막 갱신: 2026-05-28 10:48:18
window.DASHBOARD_DATA = {
  "updated": "2026-05-28 10:40:04",
  "regions": [
    {
      "name": "의정부",
      "temp": 22.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.7,
      "humid": 80,
      "level": "normal",
      "vec": 280.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 20,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 87,
          "rn1": 0.0,
          "t1h": 20.9,
          "vec": 291.0,
          "wsd": 1.3,
          "base_time": "10:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.5
        },
        "wind_dir_name": "서북서",
        "feels_like": 20.9,
        "tmax": 27.0,
        "tmin": null,
        "pop": 20,
        "hourly": [
          {
            "time": "202605281000",
            "hour": "10시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 22.0,
            "feels_like": 21.8,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 2.7,
            "wind_deg": 280.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605281100",
            "hour": "11시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 23.0,
            "feels_like": 22.7,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 3.1,
            "wind_deg": 283.0,
            "wind_dir": "서북서",
            "humid": 75
          },
          {
            "time": "202605281200",
            "hour": "12시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 23.0,
            "feels_like": 22.8,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 2.6,
            "wind_deg": 292.0,
            "wind_dir": "서북서",
            "humid": 75
          },
          {
            "time": "202605281300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 288.0,
            "wind_dir": "서북서",
            "humid": 70
          },
          {
            "time": "202605281400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 292.0,
            "wind_dir": "서북서",
            "humid": 60
          },
          {
            "time": "202605281500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.9,
            "wind_deg": 300.0,
            "wind_dir": "서북서",
            "humid": 55
          },
          {
            "time": "202605281600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.9,
            "wind_deg": 300.0,
            "wind_dir": "서북서",
            "humid": 50
          },
          {
            "time": "202605281700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.4,
            "wind_deg": 292.0,
            "wind_dir": "서북서",
            "humid": 50
          },
          {
            "time": "202605281800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 266.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202605281900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 65
          },
          {
            "time": "202605282000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 21.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.2,
            "wind_deg": 265.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605282100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 276.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605282200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 279.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605282300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 285.0,
            "wind_dir": "서북서",
            "humid": 75
          },
          {
            "time": "202605290000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 286.0,
            "wind_dir": "서북서",
            "humid": 75
          },
          {
            "time": "202605290100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 295.0,
            "wind_dir": "서북서",
            "humid": 80
          },
          {
            "time": "202605290200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 297.0,
            "wind_dir": "서북서",
            "humid": 80
          },
          {
            "time": "202605290300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 315.0,
            "wind_dir": "북서",
            "humid": 85
          },
          {
            "time": "202605290400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 335.0,
            "wind_dir": "북북서",
            "humid": 85
          },
          {
            "time": "202605290500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 337.0,
            "wind_dir": "북북서",
            "humid": 85
          },
          {
            "time": "202605290600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 356.0,
            "wind_dir": "북",
            "humid": 85
          },
          {
            "time": "202605290700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 45.0,
            "wind_dir": "북동",
            "humid": 85
          },
          {
            "time": "202605290800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 18.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 78.0,
            "wind_dir": "동북동",
            "humid": 75
          },
          {
            "time": "202605290900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.1,
            "wind_deg": 66.0,
            "wind_dir": "동북동",
            "humid": 65
          }
        ]
      }
    },
    {
      "name": "양주",
      "temp": 0,
      "weather": "?",
      "rain": 0,
      "wind": 0,
      "humid": 0,
      "level": "normal",
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 87,
          "rn1": 0.0,
          "t1h": 20.9,
          "vec": 291.0,
          "wsd": 1.3,
          "base_time": "10:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.5
        },
        "wind_dir_name": "서북서",
        "feels_like": 20.9,
        "tmax": null,
        "tmin": null,
        "pop": 0,
        "hourly": []
      }
    },
    {
      "name": "동두천",
      "temp": 22.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.9,
      "humid": 80,
      "level": "normal",
      "vec": 280.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 30,
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "서",
        "feels_like": 21.7,
        "tmax": 27.0,
        "tmin": null,
        "pop": 30,
        "hourly": [
          {
            "time": "202605281000",
            "hour": "10시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 22.0,
            "feels_like": 21.7,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.9,
            "wind_deg": 280.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605281100",
            "hour": "11시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 23.0,
            "feels_like": 22.6,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 3.3,
            "wind_deg": 287.0,
            "wind_dir": "서북서",
            "humid": 75
          },
          {
            "time": "202605281200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 288.0,
            "wind_dir": "서북서",
            "humid": 75
          },
          {
            "time": "202605281300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 285.0,
            "wind_dir": "서북서",
            "humid": 70
          },
          {
            "time": "202605281400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.5,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.7,
            "wind_deg": 295.0,
            "wind_dir": "서북서",
            "humid": 60
          },
          {
            "time": "202605281500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.9,
            "wind_deg": 298.0,
            "wind_dir": "서북서",
            "humid": 55
          },
          {
            "time": "202605281600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.8,
            "wind_deg": 297.0,
            "wind_dir": "서북서",
            "humid": 50
          },
          {
            "time": "202605281700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 290.0,
            "wind_dir": "서북서",
            "humid": 50
          },
          {
            "time": "202605281800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 280.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202605281900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 277.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202605282000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 21.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 280.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202605282100",
            "hour": "21시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 21.0,
            "feels_like": 20.9,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 2.4,
            "wind_deg": 282.0,
            "wind_dir": "서북서",
            "humid": 65
          },
          {
            "time": "202605282200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 276.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605282300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 277.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605290000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 274.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605290100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 279.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605290200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605290300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 330.0,
            "wind_dir": "북북서",
            "humid": 80
          },
          {
            "time": "202605290400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 319.0,
            "wind_dir": "북서",
            "humid": 85
          },
          {
            "time": "202605290500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 349.0,
            "wind_dir": "북",
            "humid": 85
          },
          {
            "time": "202605290600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 0.0,
            "wind_dir": "북",
            "humid": 90
          },
          {
            "time": "202605290700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 52.0,
            "wind_dir": "북동",
            "humid": 80
          },
          {
            "time": "202605290800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 68.0,
            "wind_dir": "동북동",
            "humid": 75
          },
          {
            "time": "202605290900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 45.0,
            "wind_dir": "북동",
            "humid": 65
          }
        ]
      }
    },
    {
      "name": "포천",
      "temp": 0,
      "weather": "?",
      "rain": 0,
      "wind": 0,
      "humid": 0,
      "level": "normal",
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "-",
        "feels_like": 0.0,
        "tmax": null,
        "tmin": null,
        "pop": 0,
        "hourly": []
      }
    },
    {
      "name": "연천",
      "temp": 0,
      "weather": "?",
      "rain": 0,
      "wind": 0,
      "humid": 0,
      "level": "normal",
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 92,
          "rn1": 0.0,
          "t1h": 20.5,
          "vec": 288.0,
          "wsd": 0.6,
          "base_time": "10:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.5
        },
        "wind_dir_name": "서북서",
        "feels_like": 20.5,
        "tmax": null,
        "tmin": null,
        "pop": 0,
        "hourly": []
      }
    },
    {
      "name": "가평",
      "temp": 0,
      "weather": "?",
      "rain": 0,
      "wind": 0,
      "humid": 0,
      "level": "normal",
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "-",
        "feels_like": 0.0,
        "tmax": null,
        "tmin": null,
        "pop": 0,
        "hourly": []
      }
    },
    {
      "name": "남양주",
      "temp": 22.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.7,
      "humid": 85,
      "level": "normal",
      "vec": 278.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 20,
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "서",
        "feels_like": 21.8,
        "tmax": 28.0,
        "tmin": null,
        "pop": 20,
        "hourly": [
          {
            "time": "202605281000",
            "hour": "10시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 22.0,
            "feels_like": 21.8,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 2.7,
            "wind_deg": 278.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605281100",
            "hour": "11시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 23.0,
            "feels_like": 22.7,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.9,
            "wind_deg": 276.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605281200",
            "hour": "12시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.5,
            "wind_deg": 277.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605281300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 281.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605281400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 28.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 280.0,
            "wind_dir": "서",
            "humid": 65
          },
          {
            "time": "202605281500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.4,
            "wind_deg": 292.0,
            "wind_dir": "서북서",
            "humid": 55
          },
          {
            "time": "202605281600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.7,
            "wind_deg": 295.0,
            "wind_dir": "서북서",
            "humid": 50
          },
          {
            "time": "202605281700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.4,
            "wind_deg": 292.0,
            "wind_dir": "서북서",
            "humid": 50
          },
          {
            "time": "202605281800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202605281900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 70
          },
          {
            "time": "202605282000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 21.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202605282100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 264.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605282200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605282300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605290000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 277.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605290100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 279.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605290200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 286.0,
            "wind_dir": "서북서",
            "humid": 85
          },
          {
            "time": "202605290300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 315.0,
            "wind_dir": "북서",
            "humid": 90
          },
          {
            "time": "202605290400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 347.0,
            "wind_dir": "북북서",
            "humid": 90
          },
          {
            "time": "202605290500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 347.0,
            "wind_dir": "북북서",
            "humid": 90
          },
          {
            "time": "202605290600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 0.0,
            "wind_dir": "북",
            "humid": 90
          },
          {
            "time": "202605290700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 56.0,
            "wind_dir": "북동",
            "humid": 85
          },
          {
            "time": "202605290800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 18.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 75.0,
            "wind_dir": "동북동",
            "humid": 75
          },
          {
            "time": "202605290900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 20.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 68.0,
            "wind_dir": "동북동",
            "humid": 70
          }
        ]
      }
    },
    {
      "name": "구리",
      "temp": 0,
      "weather": "?",
      "rain": 0,
      "wind": 0,
      "humid": 0,
      "level": "normal",
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 81,
          "rn1": 0.0,
          "t1h": 21.4,
          "vec": 217.0,
          "wsd": 1.0,
          "base_time": "10:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.5
        },
        "wind_dir_name": "남서",
        "feels_like": 21.4,
        "tmax": null,
        "tmin": null,
        "pop": 0,
        "hourly": []
      }
    },
    {
      "name": "파주",
      "temp": 22.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.1,
      "humid": 80,
      "level": "normal",
      "vec": 287.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 30,
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "서북서",
        "feels_like": 21.7,
        "tmax": 27.0,
        "tmin": null,
        "pop": 30,
        "hourly": [
          {
            "time": "202605281000",
            "hour": "10시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 22.0,
            "feels_like": 21.7,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 3.1,
            "wind_deg": 287.0,
            "wind_dir": "서북서",
            "humid": 80
          },
          {
            "time": "202605281100",
            "hour": "11시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 23.0,
            "feels_like": 22.6,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 3.4,
            "wind_deg": 300.0,
            "wind_dir": "서북서",
            "humid": 80
          },
          {
            "time": "202605281200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 304.0,
            "wind_dir": "북서",
            "humid": 75
          },
          {
            "time": "202605281300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 301.0,
            "wind_dir": "서북서",
            "humid": 70
          },
          {
            "time": "202605281400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.5,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.8,
            "wind_deg": 301.0,
            "wind_dir": "서북서",
            "humid": 65
          },
          {
            "time": "202605281500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 4.0,
            "wind_deg": 303.0,
            "wind_dir": "서북서",
            "humid": 55
          },
          {
            "time": "202605281600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.9,
            "wind_deg": 297.0,
            "wind_dir": "서북서",
            "humid": 55
          },
          {
            "time": "202605281700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.4,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 4.0,
            "wind_deg": 273.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202605281800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.5,
            "wind_deg": 262.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202605281900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 65
          },
          {
            "time": "202605282000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 21.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 281.0,
            "wind_dir": "서",
            "humid": 65
          },
          {
            "time": "202605282100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 20.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 288.0,
            "wind_dir": "서북서",
            "humid": 70
          },
          {
            "time": "202605282200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 19.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.2,
            "wind_deg": 280.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605282300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 284.0,
            "wind_dir": "서북서",
            "humid": 80
          },
          {
            "time": "202605290000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 277.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605290100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 295.0,
            "wind_dir": "서북서",
            "humid": 80
          },
          {
            "time": "202605290200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 279.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605290300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 278.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605290400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 333.0,
            "wind_dir": "북북서",
            "humid": 85
          },
          {
            "time": "202605290500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 333.0,
            "wind_dir": "북북서",
            "humid": 90
          },
          {
            "time": "202605290600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 349.0,
            "wind_dir": "북",
            "humid": 90
          },
          {
            "time": "202605290700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 16.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.2,
            "wind_deg": 13.0,
            "wind_dir": "북북동",
            "humid": 85
          },
          {
            "time": "202605290800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 18.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 36.0,
            "wind_dir": "북동",
            "humid": 80
          },
          {
            "time": "202605290900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 20.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 35.0,
            "wind_dir": "북동",
            "humid": 70
          }
        ]
      }
    },
    {
      "name": "고양",
      "temp": 0,
      "weather": "?",
      "rain": 0,
      "wind": 0,
      "humid": 0,
      "level": "normal",
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "-",
        "feels_like": 0.0,
        "tmax": null,
        "tmin": null,
        "pop": 0,
        "hourly": []
      }
    }
  ],
  "warnings": [],
  "rivers": [],
  "messages": [],
  "forecast": [],
  "pm": [
    {
      "region": "의정부",
      "pm10": 24,
      "pm25": 11,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "양주",
      "pm10": 24,
      "pm25": 9,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "동두천",
      "pm10": 20,
      "pm25": 7,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "포천",
      "pm10": 18,
      "pm25": 8,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "연천",
      "pm10": 27,
      "pm25": 12,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "가평",
      "pm10": 21,
      "pm25": 14,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "남양주",
      "pm10": 20,
      "pm25": 13,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "구리",
      "pm10": 21,
      "pm25": 6,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "파주",
      "pm10": 19,
      "pm25": 10,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "고양",
      "pm10": 15,
      "pm25": 14,
      "grade": "good",
      "gradeText": "좋음"
    }
  ],
  "fire": [
    {
      "region": "의정부·양주",
      "level": 1,
      "levelText": "낮음"
    },
    {
      "region": "동두천·연천",
      "level": 2,
      "levelText": "보통"
    },
    {
      "region": "포천·가평",
      "level": 1,
      "levelText": "낮음"
    },
    {
      "region": "파주·고양",
      "level": 1,
      "levelText": "낮음"
    }
  ],
  "bulletins": {
    "warnings_full": [],
    "info_list": [
      {
        "title": "[정보] 제05-121호 : 2026.05.26.18:40",
        "tmFc": "202605261840",
        "tmFc_display": "2026-05-26 18:40",
        "seq": 121
      },
      {
        "title": "[정보] 제05-120호 : 2026.05.26.18:00",
        "tmFc": "202605261800",
        "tmFc_display": "2026-05-26 18:00",
        "seq": 120
      },
      {
        "title": "[정보] 제05-119호 : 2026.05.26.16:40",
        "tmFc": "202605261640",
        "tmFc_display": "2026-05-26 16:40",
        "seq": 119
      },
      {
        "title": "[정보] 제05-118호 : 2026.05.26.13:50",
        "tmFc": "202605261350",
        "tmFc_display": "2026-05-26 13:50",
        "seq": 118
      },
      {
        "title": "[정보] 제05-117호 : 2026.05.26.09:00",
        "tmFc": "202605260900",
        "tmFc_display": "2026-05-26 09:00",
        "seq": 117
      },
      {
        "title": "[정보] 제05-116호 : 2026.05.26.06:00",
        "tmFc": "202605260600",
        "tmFc_display": "2026-05-26 06:00",
        "seq": 116
      },
      {
        "title": "[정보] 제05-115호 : 2026.05.25.20:40",
        "tmFc": "202605252040",
        "tmFc_display": "2026-05-25 20:40",
        "seq": 115
      },
      {
        "title": "[정보] 제05-114호 : 2026.05.25.18:00",
        "tmFc": "202605251800",
        "tmFc_display": "2026-05-25 18:00",
        "seq": 114
      },
      {
        "title": "[정보] 제05-113호 : 2026.05.25.06:00",
        "tmFc": "202605250600",
        "tmFc_display": "2026-05-25 06:00",
        "seq": 113
      },
      {
        "title": "[정보] 제05-112호 : 2026.05.25.05:40",
        "tmFc": "202605250540",
        "tmFc_display": "2026-05-25 05:40",
        "seq": 112
      }
    ]
  }
};
