// 자동 생성 파일. tools/update_data.py 가 매번 덮어씁니다.
// 마지막 갱신: 2026-05-30 12:57:52
window.DASHBOARD_DATA = {
  "updated": "2026-05-30 12:49:25",
  "regions": [
    {
      "name": "의정부",
      "temp": 26.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.1,
      "humid": 45,
      "level": "normal",
      "vec": 237.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 40,
          "rn1": 0.0,
          "t1h": 29.2,
          "vec": 258.0,
          "wsd": 1.4,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 29.6,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 26.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 45
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.1,
            "wind_deg": 227.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 222.0,
            "wind_dir": "남서",
            "humid": 55
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 207.0,
            "wind_dir": "남남서",
            "humid": 65
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 196.0,
            "wind_dir": "남남서",
            "humid": 70
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 75
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 139.0,
            "wind_dir": "남동",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 166.0,
            "wind_dir": "남남동",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 50
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 45
          }
        ]
      }
    },
    {
      "name": "양주",
      "temp": 26.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.1,
      "humid": 50,
      "level": "normal",
      "vec": 237.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 40,
          "rn1": 0.0,
          "t1h": 29.2,
          "vec": 258.0,
          "wsd": 1.4,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 29.6,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 50
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 251.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 27.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.1,
            "wind_deg": 227.0,
            "wind_dir": "남서",
            "humid": 55
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 214.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 207.0,
            "wind_dir": "남남서",
            "humid": 70
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 191.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 127.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 90
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 153.0,
            "wind_dir": "남남동",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 172.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 45
          }
        ]
      }
    },
    {
      "name": "동두천",
      "temp": 27.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.9,
      "humid": 45,
      "level": "normal",
      "vec": 237.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 39,
          "rn1": 0.0,
          "t1h": 27.5,
          "vec": 253.0,
          "wsd": 2.7,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 27.3,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 239.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 232.0,
            "wind_dir": "남서",
            "humid": 45
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.1,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 223.0,
            "wind_dir": "남서",
            "humid": 55
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 214.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 188.0,
            "wind_dir": "남",
            "humid": 65
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 186.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 149.0,
            "wind_dir": "남남동",
            "humid": 85
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 164.0,
            "wind_dir": "남남동",
            "humid": 85
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 164.0,
            "wind_dir": "남남동",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 45
          }
        ]
      }
    },
    {
      "name": "포천",
      "temp": 26.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.8,
      "humid": 45,
      "level": "normal",
      "vec": 243.0,
      "tmax": 29.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 46,
          "rn1": 0.0,
          "t1h": 28.4,
          "vec": 225.0,
          "wsd": 2.2,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "남서",
        "feels_like": 28.8,
        "tmax": 29.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.9,
            "wind_deg": 260.0,
            "wind_dir": "서",
            "humid": 40
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.4,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 242.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 232.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 65
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 143.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 131.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 106.0,
            "wind_dir": "동남동",
            "humid": 85
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 127.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 162.0,
            "wind_dir": "남남동",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 191.0,
            "wind_dir": "남",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "연천",
      "temp": 27.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.8,
      "humid": 50,
      "level": "normal",
      "vec": 231.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 42,
          "rn1": 0.0,
          "t1h": 28.4,
          "vec": 155.0,
          "wsd": 2.1,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "남남동",
        "feels_like": 28.3,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 27.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 231.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 50
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.5,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 45
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.3,
            "wind_deg": 227.0,
            "wind_dir": "남서",
            "humid": 45
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.5,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 221.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 223.0,
            "wind_dir": "남서",
            "humid": 55
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 201.0,
            "wind_dir": "남남서",
            "humid": 60
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 80
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 90
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 90
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 65
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 184.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 214.0,
            "wind_dir": "남서",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "가평",
      "temp": 27.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.4,
      "humid": 45,
      "level": "normal",
      "vec": 232.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 42,
          "rn1": 0.0,
          "t1h": 28.2,
          "vec": 219.0,
          "wsd": 3.2,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "남서",
        "feels_like": 27.3,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 232.0,
            "wind_dir": "남서",
            "humid": 45
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 241.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 228.0,
            "wind_dir": "남서",
            "humid": 40
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 207.0,
            "wind_dir": "남남서",
            "humid": 45
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 65
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 80
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "남양주",
      "temp": 27.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.8,
      "humid": 45,
      "level": "normal",
      "vec": 243.0,
      "tmax": 29.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 41,
          "rn1": 0.0,
          "t1h": 29.6,
          "vec": 267.0,
          "wsd": 2.1,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서",
        "feels_like": 29.8,
        "tmax": 29.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.4,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.5,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.5,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 29.4,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 239.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 27.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 245.0,
            "wind_dir": "서남서",
            "humid": 50
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 55
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 70
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 0.0,
            "wind_dir": "북",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 0.0,
            "wind_dir": "북",
            "humid": 80
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 80
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 106.0,
            "wind_dir": "동남동",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 143.0,
            "wind_dir": "남동",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 174.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 50
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 191.0,
            "wind_dir": "남",
            "humid": 45
          }
        ]
      }
    },
    {
      "name": "구리",
      "temp": 27.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.0,
      "humid": 45,
      "level": "normal",
      "vec": 249.0,
      "tmax": 29.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 35,
          "rn1": 0.0,
          "t1h": 28.7,
          "vec": 186.0,
          "wsd": 3.1,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "남",
        "feels_like": 28.4,
        "tmax": 29.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 26.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 255.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 29.0,
            "feels_like": 28.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 40
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 241.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 27.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 242.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 241.0,
            "wind_dir": "서남서",
            "humid": 55
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 239.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 164.0,
            "wind_dir": "남남동",
            "humid": 65
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 50
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 45
          }
        ]
      }
    },
    {
      "name": "파주",
      "temp": 25.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.5,
      "humid": 50,
      "level": "normal",
      "vec": 225.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 53,
          "rn1": 0.0,
          "t1h": 26.8,
          "vec": 238.0,
          "wsd": 3.6,
          "base_time": "12:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 26.3,
        "tmax": 27.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.5,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.5,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.6,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.4,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.6,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.3,
            "wind_deg": 227.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 26.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.3,
            "wind_deg": 223.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 218.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 209.0,
            "wind_dir": "남남서",
            "humid": 55
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 193.0,
            "wind_dir": "남남서",
            "humid": 60
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 184.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 143.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 131.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 127.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 90
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 159.0,
            "wind_dir": "남남동",
            "humid": 85
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 169.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 65
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 184.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 223.0,
            "wind_dir": "남서",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "고양",
      "temp": 26.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.2,
      "humid": 50,
      "level": "normal",
      "vec": 231.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {},
        "rain_cumul": {
          "1h": 0,
          "3h": 0,
          "6h": 0,
          "12h": 0
        },
        "wind_dir_name": "남서",
        "feels_like": 25.6,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202605301200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 231.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301300",
            "hour": "13시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 50
          },
          {
            "time": "202605301400",
            "hour": "14시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 27.3,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.3,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 45
          },
          {
            "time": "202605301500",
            "hour": "15시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 50
          },
          {
            "time": "202605301600",
            "hour": "16시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 28.0,
            "feels_like": 28.2,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.0,
            "wind_deg": 229.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301700",
            "hour": "17시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 27.0,
            "feels_like": 27.1,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 50
          },
          {
            "time": "202605301900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 209.0,
            "wind_dir": "남남서",
            "humid": 60
          },
          {
            "time": "202605302000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 191.0,
            "wind_dir": "남",
            "humid": 70
          },
          {
            "time": "202605302100",
            "hour": "21시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 188.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202605302300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202605310000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202605310100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.1,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202605310200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202605310300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.2,
            "wind_deg": 135.0,
            "wind_dir": "남동",
            "humid": 85
          },
          {
            "time": "202605310400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 85
          },
          {
            "time": "202605310500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 90.0,
            "wind_dir": "동",
            "humid": 90
          },
          {
            "time": "202605310600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 121.0,
            "wind_dir": "동남동",
            "humid": 90
          },
          {
            "time": "202605310700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 153.0,
            "wind_dir": "남남동",
            "humid": 80
          },
          {
            "time": "202605310800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 166.0,
            "wind_dir": "남남동",
            "humid": 70
          },
          {
            "time": "202605310900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 60
          },
          {
            "time": "202605311000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 188.0,
            "wind_dir": "남",
            "humid": 55
          },
          {
            "time": "202605311100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 26.0,
            "feels_like": 26.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 50
          }
        ]
      }
    }
  ],
  "warnings": [],
  "rivers": [],
  "messages": [],
  "forecast": [],
  "pm": [
    {
      "region": "의정부",
      "pm10": 42,
      "pm25": 18,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "양주",
      "pm10": 39,
      "pm25": 21,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "동두천",
      "pm10": 36,
      "pm25": 10,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "포천",
      "pm10": 36,
      "pm25": 13,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "연천",
      "pm10": 32,
      "pm25": 24,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "가평",
      "pm10": 25,
      "pm25": 20,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "남양주",
      "pm10": 26,
      "pm25": 21,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "구리",
      "pm10": 41,
      "pm25": 8,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "파주",
      "pm10": 50,
      "pm25": 24,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "고양",
      "pm10": 50,
      "pm25": 16,
      "grade": "normal",
      "gradeText": "보통"
    }
  ],
  "fire": [
    {
      "region": "의정부·양주",
      "level": 3,
      "levelText": "높음"
    },
    {
      "region": "동두천·연천",
      "level": 2,
      "levelText": "보통"
    },
    {
      "region": "포천·가평",
      "level": 2,
      "levelText": "보통"
    },
    {
      "region": "파주·고양",
      "level": 2,
      "levelText": "보통"
    }
  ],
  "bulletins": {
    "warnings_full": [],
    "info_list": [
      {
        "title": "[정보] 제05-132호 : 2026.05.28.06:00",
        "tmFc": "202605280600",
        "tmFc_display": "2026-05-28 06:00",
        "seq": 132
      },
      {
        "title": "[정보] 제05-131호 : 2026.05.28.05:30",
        "tmFc": "202605280530",
        "tmFc_display": "2026-05-28 05:30",
        "seq": 131
      },
      {
        "title": "[정보] 제05-130호 : 2026.05.28.05:10",
        "tmFc": "202605280510",
        "tmFc_display": "2026-05-28 05:10",
        "seq": 130
      },
      {
        "title": "[정보] 제05-129호 : 2026.05.27.22:10",
        "tmFc": "202605272210",
        "tmFc_display": "2026-05-27 22:10",
        "seq": 129
      },
      {
        "title": "[정보] 제05-128호 : 2026.05.27.20:40",
        "tmFc": "202605272040",
        "tmFc_display": "2026-05-27 20:40",
        "seq": 128
      },
      {
        "title": "[정보] 제05-127호 : 2026.05.27.18:00",
        "tmFc": "202605271800",
        "tmFc_display": "2026-05-27 18:00",
        "seq": 127
      },
      {
        "title": "[정보] 제05-126호 : 2026.05.27.14:10",
        "tmFc": "202605271410",
        "tmFc_display": "2026-05-27 14:10",
        "seq": 126
      },
      {
        "title": "[정보] 제05-125호 : 2026.05.27.07:00",
        "tmFc": "202605270700",
        "tmFc_display": "2026-05-27 07:00",
        "seq": 125
      },
      {
        "title": "[정보] 제05-124호 : 2026.05.27.06:10",
        "tmFc": "202605270610",
        "tmFc_display": "2026-05-27 06:10",
        "seq": 124
      },
      {
        "title": "[정보] 제05-123호 : 2026.05.27.06:00",
        "tmFc": "202605270600",
        "tmFc_display": "2026-05-27 06:00",
        "seq": 123
      }
    ]
  }
};
