// 자동 생성 파일. tools/update_data.py 가 매번 덮어씁니다.
// 마지막 갱신: 2026-06-11 11:59:24
window.DASHBOARD_DATA = {
  "updated": "2026-06-11 11:50:54",
  "regions": [
    {
      "name": "의정부",
      "temp": 24.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.1,
      "humid": 50,
      "level": "normal",
      "vec": 272.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 49,
          "rn1": 0.0,
          "t1h": 24.0,
          "vec": 243.0,
          "wsd": 1.7,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 24.0,
        "tmax": 27.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 50
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 3.2,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.2,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.3,
            "wind_deg": 263.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 2.9,
            "wind_deg": 260.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.8,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 2.7,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 8.0,
            "rain_pop": 60,
            "wind_ms": 1.1,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 65
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.3,
            "wind_deg": 222.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.8,
            "wind_deg": 221.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.7,
            "wind_deg": 218.0,
            "wind_dir": "남서",
            "humid": 75
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 259.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 239.0,
            "wind_dir": "서남서",
            "humid": 95
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 229.0,
            "wind_dir": "남서",
            "humid": 85
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 258.0,
            "wind_dir": "서남서",
            "humid": 65
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 259.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 253.0,
            "wind_dir": "서남서",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "양주",
      "temp": 24.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.2,
      "humid": 50,
      "level": "normal",
      "vec": 272.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 49,
          "rn1": 0.0,
          "t1h": 24.0,
          "vec": 243.0,
          "wsd": 1.7,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 24.0,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.2,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 50
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 3.3,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.4,
            "wind_deg": 265.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.5,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.2,
            "wind_deg": 263.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.7,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.0,
            "wind_deg": 262.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 6.0,
            "rain_pop": 60,
            "wind_ms": 1.4,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 65
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 1.5,
            "wind_deg": 235.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 1.8,
            "wind_deg": 229.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 1.7,
            "wind_deg": 220.0,
            "wind_dir": "남서",
            "humid": 75
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 228.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 255.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 264.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 231.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 207.0,
            "wind_dir": "남남서",
            "humid": 95
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 230.0,
            "wind_dir": "남서",
            "humid": 85
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 247.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.2,
            "wind_deg": 252.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 55
          }
        ]
      }
    },
    {
      "name": "동두천",
      "temp": 24.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.7,
      "humid": 55,
      "level": "normal",
      "vec": 270.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 46,
          "rn1": 0.0,
          "t1h": 24.3,
          "vec": 258.0,
          "wsd": 2.4,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서남서",
        "feels_like": 24.2,
        "tmax": 27.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.2,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.7,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.0,
            "wind_deg": 264.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.2,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 2.7,
            "wind_deg": 266.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 2.4,
            "wind_deg": 258.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 2.0,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.7,
            "wind_deg": 223.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.5,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.5,
            "wind_deg": 215.0,
            "wind_dir": "남서",
            "humid": 75
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 228.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 252.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 249.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 240.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 210.0,
            "wind_dir": "남남서",
            "humid": 90
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 196.0,
            "wind_dir": "남남서",
            "humid": 90
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 85
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 247.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 253.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 55
          }
        ]
      }
    },
    {
      "name": "포천",
      "temp": 23.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.7,
      "humid": 55,
      "level": "normal",
      "vec": 272.0,
      "tmax": 26.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 56,
          "rn1": 0.0,
          "t1h": 22.8,
          "vec": 315.0,
          "wsd": 2.8,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "북서",
        "feels_like": 22.6,
        "tmax": 26.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.7,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 3.0,
            "wind_deg": 278.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.0,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.1,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 2.2,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 5.0,
            "rain_pop": 60,
            "wind_ms": 2.4,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 6.0,
            "rain_pop": 60,
            "wind_ms": 1.6,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.2,
            "wind_deg": 228.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 0.7,
            "wind_deg": 188.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 80
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 185.0,
            "wind_dir": "남",
            "humid": 85
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 207.0,
            "wind_dir": "남남서",
            "humid": 85
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 230.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 229.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 239.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 13.0,
            "feels_like": 13.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 211.0,
            "wind_dir": "남남서",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 13.0,
            "feels_like": 13.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 194.0,
            "wind_dir": "남남서",
            "humid": 95
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 247.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 261.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 261.0,
            "wind_dir": "서",
            "humid": 55
          }
        ]
      }
    },
    {
      "name": "연천",
      "temp": 24.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.6,
      "humid": 55,
      "level": "normal",
      "vec": 268.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 57,
          "rn1": 0.0,
          "t1h": 23.5,
          "vec": 284.0,
          "wsd": 2.0,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서북서",
        "feels_like": 23.5,
        "tmax": 27.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 2.8,
            "wind_deg": 264.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 2.0,
            "wind_deg": 259.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 25.0,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 1.8,
            "wind_deg": 267.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 1.3,
            "wind_deg": 240.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 2.5,
            "wind_deg": 241.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 1.7,
            "wind_deg": 216.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 192.0,
            "wind_dir": "남남서",
            "humid": 70
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 0.8,
            "wind_deg": 194.0,
            "wind_dir": "남남서",
            "humid": 75
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 1.1,
            "wind_deg": 190.0,
            "wind_dir": "남",
            "humid": 75
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 211.0,
            "wind_dir": "남남서",
            "humid": 80
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 261.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 198.0,
            "wind_dir": "남남서",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 194.0,
            "wind_dir": "남남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 95
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 13.0,
            "feels_like": 13.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.3,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.6,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 95
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 194.0,
            "wind_dir": "남남서",
            "humid": 85
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 212.0,
            "wind_dir": "남남서",
            "humid": 80
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.1,
            "wind_deg": 232.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 238.0,
            "wind_dir": "서남서",
            "humid": 65
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 247.0,
            "wind_dir": "서남서",
            "humid": 55
          }
        ]
      }
    },
    {
      "name": "가평",
      "temp": 24.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.6,
      "humid": 55,
      "level": "normal",
      "vec": 268.0,
      "tmax": 25.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 51,
          "rn1": 0.0,
          "t1h": 24.7,
          "vec": 259.0,
          "wsd": 1.5,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서",
        "feels_like": 24.7,
        "tmax": 25.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.6,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.6,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 50
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.7,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.6,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 3.4,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 1.7,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 1.2,
            "wind_deg": 261.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 0.7,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 65
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 0.9,
            "wind_deg": 204.0,
            "wind_dir": "남남서",
            "humid": 75
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 1.0,
            "wind_deg": 202.0,
            "wind_dir": "남남서",
            "humid": 75
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 0.9,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 0.9,
            "wind_deg": 204.0,
            "wind_dir": "남남서",
            "humid": 85
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 1.0,
            "wind_deg": 202.0,
            "wind_dir": "남남서",
            "humid": 85
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 186.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 0.9,
            "wind_deg": 174.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 14.0,
            "feels_like": 14.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 174.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 90
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 235.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 258.0,
            "wind_dir": "서남서",
            "humid": 55
          }
        ]
      }
    },
    {
      "name": "남양주",
      "temp": 25.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.5,
      "humid": 50,
      "level": "normal",
      "vec": 272.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 44,
          "rn1": 0.0,
          "t1h": 27.6,
          "vec": 299.0,
          "wsd": 2.6,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서북서",
        "feels_like": 27.2,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.5,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 50
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.7,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 2.9,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 27.0,
            "feels_like": 28.0,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.1,
            "wind_deg": 268.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 27.0,
            "feels_like": 27.9,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.3,
            "wind_deg": 263.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.7,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.0,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.9,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 2.5,
            "wind_deg": 259.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 8.0,
            "rain_pop": 60,
            "wind_ms": 1.6,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 1.2,
            "wind_deg": 231.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 1.5,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 1.2,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 219.0,
            "wind_dir": "남서",
            "humid": 75
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 230.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 230.0,
            "wind_dir": "남서",
            "humid": 85
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 240.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 230.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.4,
            "wind_deg": 194.0,
            "wind_dir": "남남서",
            "humid": 90
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 252.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 262.0,
            "wind_dir": "서",
            "humid": 65
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 258.0,
            "wind_dir": "서남서",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "구리",
      "temp": 25.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 2.8,
      "humid": 45,
      "level": "normal",
      "vec": 272.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 44,
          "rn1": 0.0,
          "t1h": 24.5,
          "vec": 260.0,
          "wsd": 2.8,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서",
        "feels_like": 24.3,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.8,
            "wind_deg": 272.0,
            "wind_dir": "서",
            "humid": 45
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 26.0,
            "feels_like": 25.5,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 3.6,
            "wind_deg": 270.0,
            "wind_dir": "서",
            "humid": 45
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 27.0,
            "feels_like": 27.7,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.5,
            "wind_deg": 260.0,
            "wind_dir": "서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 27.0,
            "feels_like": 27.6,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.7,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.4,
            "wind_deg": 258.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 3.1,
            "wind_deg": 250.0,
            "wind_dir": "서남서",
            "humid": 50
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 24.0,
            "rain_mm": 7.0,
            "rain_pop": 60,
            "wind_ms": 1.9,
            "wind_deg": 258.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 1.6,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 22.0,
            "feels_like": 21.9,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 2.4,
            "wind_deg": 222.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 2.0,
            "wind_deg": 223.0,
            "wind_dir": "남서",
            "humid": 65
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.7,
            "wind_deg": 220.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 240.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 239.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.5,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 85
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 256.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 262.0,
            "wind_dir": "서",
            "humid": 65
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 55
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.2,
            "wind_deg": 252.0,
            "wind_dir": "서남서",
            "humid": 50
          }
        ]
      }
    },
    {
      "name": "파주",
      "temp": 24.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.3,
      "humid": 55,
      "level": "normal",
      "vec": 261.0,
      "tmax": 27.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 54,
          "rn1": 0.0,
          "t1h": 24.6,
          "vec": 270.0,
          "wsd": 2.8,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서",
        "feels_like": 24.4,
        "tmax": 27.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.6,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.3,
            "wind_deg": 261.0,
            "wind_dir": "서",
            "humid": 55
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 1.0,
            "rain_pop": 60,
            "wind_ms": 3.5,
            "wind_deg": 252.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.5,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 3.6,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.4,
            "wind_deg": 242.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.4,
            "wind_deg": 234.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 24.0,
            "feels_like": 23.7,
            "rain_mm": 3.0,
            "rain_pop": 60,
            "wind_ms": 2.9,
            "wind_deg": 232.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 23.0,
            "feels_like": 22.9,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.2,
            "wind_deg": 232.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "☁",
            "weather": "흐림",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 30,
            "wind_ms": 2.1,
            "wind_deg": 210.0,
            "wind_dir": "남남서",
            "humid": 60
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 19.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 211.0,
            "wind_dir": "남남서",
            "humid": 65
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 1.9,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.6,
            "wind_deg": 245.0,
            "wind_dir": "서남서",
            "humid": 75
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.8,
            "wind_deg": 264.0,
            "wind_dir": "서",
            "humid": 80
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 266.0,
            "wind_dir": "서",
            "humid": 85
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 261.0,
            "wind_dir": "서",
            "humid": 90
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.9,
            "wind_deg": 246.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 214.0,
            "wind_dir": "남서",
            "humid": 95
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 188.0,
            "wind_dir": "남",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 15.0,
            "feels_like": 15.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 180.0,
            "wind_dir": "남",
            "humid": 95
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 238.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 22.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.4,
            "wind_deg": 240.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 24.0,
            "feels_like": 23.8,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.7,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 55
          }
        ]
      }
    },
    {
      "name": "고양",
      "temp": 25.0,
      "weather": "맑음",
      "rain": 0,
      "wind": 3.1,
      "humid": 50,
      "level": "normal",
      "vec": 259.0,
      "tmax": 28.0,
      "tmin": null,
      "pop": 0,
      "detail": {
        "observation": {
          "pty": "0",
          "reh": 49,
          "rn1": 0.0,
          "t1h": 26.1,
          "vec": 287.0,
          "wsd": 2.8,
          "base_time": "11:00"
        },
        "rain_cumul": {
          "1h": 0.0,
          "3h": 0.0,
          "6h": 0.0,
          "12h": 0.0
        },
        "wind_dir_name": "서북서",
        "feels_like": 25.9,
        "tmax": 28.0,
        "tmin": null,
        "pop": 0,
        "hourly": [
          {
            "time": "202606111200",
            "hour": "12시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 3.1,
            "wind_deg": 259.0,
            "wind_dir": "서",
            "humid": 50
          },
          {
            "time": "202606111300",
            "hour": "13시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 0,
            "rain_pop": 60,
            "wind_ms": 3.2,
            "wind_deg": 254.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111400",
            "hour": "14시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.3,
            "wind_deg": 247.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111500",
            "hour": "15시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 26.0,
            "feels_like": 25.6,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.5,
            "wind_deg": 243.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111600",
            "hour": "16시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.6,
            "rain_mm": 4.0,
            "rain_pop": 60,
            "wind_ms": 3.3,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111700",
            "hour": "17시",
            "icon": "🌧",
            "weather": "소나기",
            "temp": 25.0,
            "feels_like": 24.7,
            "rain_mm": 2.0,
            "rain_pop": 60,
            "wind_ms": 3.1,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 60
          },
          {
            "time": "202606111800",
            "hour": "18시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.9,
            "wind_deg": 229.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606111900",
            "hour": "19시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 22.0,
            "feels_like": 22.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 1.8,
            "wind_deg": 199.0,
            "wind_dir": "남남서",
            "humid": 65
          },
          {
            "time": "202606112000",
            "hour": "20시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 2.1,
            "wind_deg": 210.0,
            "wind_dir": "남남서",
            "humid": 70
          },
          {
            "time": "202606112100",
            "hour": "21시",
            "icon": "🌥",
            "weather": "구름많음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 20,
            "wind_ms": 1.9,
            "wind_deg": 215.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606112200",
            "hour": "22시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 19.0,
            "feels_like": 19.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 217.0,
            "wind_dir": "남서",
            "humid": 75
          },
          {
            "time": "202606112300",
            "hour": "23시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.5,
            "wind_deg": 259.0,
            "wind_dir": "서",
            "humid": 75
          },
          {
            "time": "202606120000",
            "hour": "0시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.3,
            "wind_deg": 257.0,
            "wind_dir": "서남서",
            "humid": 80
          },
          {
            "time": "202606120100",
            "hour": "1시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 85
          },
          {
            "time": "202606120200",
            "hour": "2시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 17.0,
            "feels_like": 17.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.0,
            "wind_deg": 248.0,
            "wind_dir": "서남서",
            "humid": 90
          },
          {
            "time": "202606120300",
            "hour": "3시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 236.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120400",
            "hour": "4시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 90
          },
          {
            "time": "202606120500",
            "hour": "5시",
            "icon": "🌙",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.7,
            "wind_deg": 203.0,
            "wind_dir": "남남서",
            "humid": 95
          },
          {
            "time": "202606120600",
            "hour": "6시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 16.0,
            "feels_like": 16.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 0.8,
            "wind_deg": 210.0,
            "wind_dir": "남남서",
            "humid": 95
          },
          {
            "time": "202606120700",
            "hour": "7시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 18.0,
            "feels_like": 18.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 231.0,
            "wind_dir": "남서",
            "humid": 85
          },
          {
            "time": "202606120800",
            "hour": "8시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 20.0,
            "feels_like": 20.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.2,
            "wind_deg": 225.0,
            "wind_dir": "남서",
            "humid": 80
          },
          {
            "time": "202606120900",
            "hour": "9시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 21.0,
            "feels_like": 21.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 1.4,
            "wind_deg": 228.0,
            "wind_dir": "남서",
            "humid": 70
          },
          {
            "time": "202606121000",
            "hour": "10시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 23.0,
            "feels_like": 23.0,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.0,
            "wind_deg": 233.0,
            "wind_dir": "남서",
            "humid": 60
          },
          {
            "time": "202606121100",
            "hour": "11시",
            "icon": "☀",
            "weather": "맑음",
            "temp": 25.0,
            "feels_like": 24.9,
            "rain_mm": 0,
            "rain_pop": 0,
            "wind_ms": 2.3,
            "wind_deg": 237.0,
            "wind_dir": "서남서",
            "humid": 50
          }
        ]
      }
    }
  ],
  "warnings": [],
  "rivers": [],
  "messages": [],
  "forecast": [
    {
      "time": "12시",
      "icon": "☀",
      "temp": 24,
      "rain": 0
    },
    {
      "time": "13시",
      "icon": "🌧",
      "temp": 25,
      "rain": 60
    },
    {
      "time": "14시",
      "icon": "🌧",
      "temp": 26,
      "rain": 60
    },
    {
      "time": "15시",
      "icon": "🌧",
      "temp": 25,
      "rain": 60
    },
    {
      "time": "16시",
      "icon": "🌧",
      "temp": 25,
      "rain": 60
    },
    {
      "time": "17시",
      "icon": "🌧",
      "temp": 24,
      "rain": 60
    },
    {
      "time": "18시",
      "icon": "🌧",
      "temp": 22,
      "rain": 60
    },
    {
      "time": "19시",
      "icon": "🌧",
      "temp": 21,
      "rain": 60
    },
    {
      "time": "20시",
      "icon": "🌧",
      "temp": 20,
      "rain": 60
    },
    {
      "time": "21시",
      "icon": "🌧",
      "temp": 19,
      "rain": 60
    },
    {
      "time": "22시",
      "icon": "🌙",
      "temp": 18,
      "rain": 0
    },
    {
      "time": "23시",
      "icon": "🌙",
      "temp": 17,
      "rain": 0
    }
  ],
  "pm": [
    {
      "region": "의정부",
      "pm10": 28,
      "pm25": 22,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "양주",
      "pm10": 31,
      "pm25": 21,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "동두천",
      "pm10": 30,
      "pm25": 9,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "포천",
      "pm10": 11,
      "pm25": 3,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "연천",
      "pm10": 19,
      "pm25": 16,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "가평",
      "pm10": 30,
      "pm25": 11,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "남양주",
      "pm10": 24,
      "pm25": 7,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "구리",
      "pm10": 26,
      "pm25": 8,
      "grade": "good",
      "gradeText": "좋음"
    },
    {
      "region": "파주",
      "pm10": 32,
      "pm25": 19,
      "grade": "normal",
      "gradeText": "보통"
    },
    {
      "region": "고양",
      "pm10": 32,
      "pm25": 20,
      "grade": "normal",
      "gradeText": "보통"
    }
  ],
  "fire": [
    {
      "region": "의정부·양주",
      "level": 2,
      "levelText": "보통"
    },
    {
      "region": "동두천·연천",
      "level": 1,
      "levelText": "낮음"
    },
    {
      "region": "포천·가평",
      "level": 1,
      "levelText": "낮음"
    },
    {
      "region": "파주·고양",
      "level": 1,
      "levelText": "낮음"
    }
  ],
  "bulletins": {
    "warnings_full": [],
    "info_list": [
      {
        "title": "[정보] 제06-45호 : 2026.06.10.06:00",
        "tmFc": "202606100600",
        "tmFc_display": "2026-06-10 06:00",
        "seq": 45
      },
      {
        "title": "[정보] 제06-44호 : 2026.06.10.03:40",
        "tmFc": "202606100340",
        "tmFc_display": "2026-06-10 03:40",
        "seq": 44
      },
      {
        "title": "[정보] 제06-43호 : 2026.06.09.22:10",
        "tmFc": "202606092210",
        "tmFc_display": "2026-06-09 22:10",
        "seq": 43
      },
      {
        "title": "[정보] 제06-42호 : 2026.06.09.19:50",
        "tmFc": "202606091950",
        "tmFc_display": "2026-06-09 19:50",
        "seq": 42
      },
      {
        "title": "[정보] 제06-41호 : 2026.06.09.18:00",
        "tmFc": "202606091800",
        "tmFc_display": "2026-06-09 18:00",
        "seq": 41
      },
      {
        "title": "[정보] 제06-40호 : 2026.06.09.12:50",
        "tmFc": "202606091250",
        "tmFc_display": "2026-06-09 12:50",
        "seq": 40
      },
      {
        "title": "[정보] 제06-39호 : 2026.06.09.10:00",
        "tmFc": "202606091000",
        "tmFc_display": "2026-06-09 10:00",
        "seq": 39
      },
      {
        "title": "[정보] 제06-38호 : 2026.06.09.06:00",
        "tmFc": "202606090600",
        "tmFc_display": "2026-06-09 06:00",
        "seq": 38
      },
      {
        "title": "[정보] 제06-37호 : 2026.06.08.18:00",
        "tmFc": "202606081800",
        "tmFc_display": "2026-06-08 18:00",
        "seq": 37
      },
      {
        "title": "[정보] 제06-36호 : 2026.06.08.06:00",
        "tmFc": "202606080600",
        "tmFc_display": "2026-06-08 06:00",
        "seq": 36
      }
    ]
  }
};
